<?php
/**
 * TL_ROOT/system/modules/tags_articles/languages/nl/modules.php 
 * 
 * Contao extension: tags_articles 1.2.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloudarticles']['0'] = "Tag Cloud (artikelen)";
$GLOBALS['TL_LANG']['FMD']['tagcloudarticles']['1'] = "Deze module toont een tag cloud voor geselecteerde Contao artikelen.";
$GLOBALS['TL_LANG']['FMD']['taggedArticleList']['0'] = "Artikellijst (Tags)";
$GLOBALS['TL_LANG']['FMD']['taggedArticleList']['1'] = "Deze module genereert een lijst van artikelen van een kolom in een geselecteerde tak van de website en kan gefilterd worden door een tag cloud.";
 
?>
