<?php
/**
 * TL_ROOT/system/modules/tags_articles/languages/nl/tl_module.php 
 * 
 * Contao extension: tags_articles 1.2.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_articles']['0'] = "Artikelen";
$GLOBALS['TL_LANG']['tl_module']['tag_articles']['1'] = "Kies de pagina's waarvan de artikelen gebruikt worden om de tag cloud te maken. Als u een pagina kiest die subpagina's heeft, dan zullen de artikelen van de subpagina's ook gebruikt worden.";
$GLOBALS['TL_LANG']['tl_module']['show_in_column']['0'] = "Beperk tot bepaalde kolom";
$GLOBALS['TL_LANG']['tl_module']['show_in_column']['1'] = "Beperk het resultaat van de artikellijst tot een bepaalde kolom van de pagina template.";
$GLOBALS['TL_LANG']['tl_module']['linktoarticles']['0'] = "Artikellijst linkt naar artikelen";
$GLOBALS['TL_LANG']['tl_module']['linktoarticles']['1'] = "Kies om een artikellijst te maken met links naar de artikelen. Of kies niet om een artikellijst te maken met links naar de omhullende pagina.";
$GLOBALS['TL_LANG']['tl_module']['restrict_to_column']['0'] = "Beperk tot bepaalde kolom";
$GLOBALS['TL_LANG']['tl_module']['restrict_to_column']['1'] = "Beperk de tag cloud tot tags van artikelen die in een bepaalde kolom van het pagina template staan.";
$GLOBALS['TL_LANG']['tl_module']['articlelist_tpl']['0'] = "Artikellijst template";
$GLOBALS['TL_LANG']['tl_module']['articlelist_tpl']['1'] = "Kies de artikellijst template.";
$GLOBALS['TL_LANG']['tl_module']['article_showtags']['0'] = "Toon artikel tags";
$GLOBALS['TL_LANG']['tl_module']['article_showtags']['1'] = "Kies deze optie om alle passende tags onder elk artikel te tonen. Dit werkt alleen als u een specifiek artikel template gebruikt, bijvoorbeeld mod_global_articlelist.";
 
?>
