<?php
/**
 * TL_ROOT/system/modules/tags_articles/languages/de/tl_module.php 
 * 
 * TYPOlight extension: tags_articles 1.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_articles']['0'] = "Artikel";
$GLOBALS['TL_LANG']['tl_module']['tag_articles']['1'] = "Bitte wählen Sie die Seite aus, deren Artikel zur Erstellung der Tag Cloud verwendet werden sollen. Wenn die Seite Unterseiten besitzt, so werden diese Artikel ebenfalls für die Generierung der Tag Cloud verwendet.";
$GLOBALS['TL_LANG']['tl_module']['show_in_column']['0'] = "Auswahl auf eine bestimmt Spalte einschränken";
$GLOBALS['TL_LANG']['tl_module']['show_in_column']['1'] = "Schränken Sie die Auswahl der Artikelliste auf Artikel aus einer bestimmten Spalte eines Seitentemplates ein.";
$GLOBALS['TL_LANG']['tl_module']['linktoarticles']['0'] = "Weiterführende Links auf Artikel";
$GLOBALS['TL_LANG']['tl_module']['linktoarticles']['1'] = "Wählen Sie diese Option, wenn die weiterführenden Links der Artikelliste auf die Artikel verweisen sollen oder entfernen Sie diese Option, um auf die beinhaltenden Seiten der Artikel zu verweisen.";
$GLOBALS['TL_LANG']['tl_module']['restrict_to_column']['0'] = "Auswahl auf eine bestimmt Spalte einschränken";
$GLOBALS['TL_LANG']['tl_module']['restrict_to_column']['1'] = "Schränken Sie die Tag Cloud auf Tags von Artikeln aus einer bestimmten Spalte eines Seitentemplates ein.";
$GLOBALS['TL_LANG']['tl_module']['articlelist_tpl']['0'] = "Artikellisten-Template";
$GLOBALS['TL_LANG']['tl_module']['articlelist_tpl']['1'] = "Hier können Sie das Artikellisten-Template auswählen.";
$GLOBALS['TL_LANG']['tl_module']['article_showtags']['0'] = "Artikel-Auszeichnungen anzeigen";
$GLOBALS['TL_LANG']['tl_module']['article_showtags']['1'] = "Wählen Sie diese Option aus, um die zu einem Artikel zugehörigen Auszeichnungen unter dem Artikel anzuzeigen. Diese Einstellung funktioniert nur, wenn Sie ein Artikel-Template verwenden, das für die Ausgabe von Auszeichnungen vorgesehen wurde, wie z.B. mod_global_articlelist";
$GLOBALS['TL_LANG']['tl_module']['articlelist_firstorder'] = array('Erstes Sortierkriterium', 'Wählen Sie das erste Sortierkriterium für die Artikelliste aus.');
$GLOBALS['TL_LANG']['tl_module']['articlelist_secondorder'] = array('Zweites Sortierkriterium', 'Wählen Sie das zweite Sortierkriterium für die Artikelliste aus.');

?>
